import { ADD_TODO, MARKED_AS_DONE, EDIT_TODO, DELETE_TODO, FIREBASE_FETCH_ALL } from "../actions/actionType";
import v4 from 'uuid/v4';
import _ from 'lodash';

const todos = (state=[], {type, payload}) => {
    switch(type){
        case ADD_TODO:
            return [
                ...state,
                { 
                    name: payload.todoText,
                    uuid: payload.autoGeneratedKey,
                    done: false,
                    saveLocalStorage: false,
                    savedFirebase: true,
                }
            ]
        case MARKED_AS_DONE: 
            let currentSelected = state.filter(obj => {
                return (obj.uuid) === payload.uuid;
            })[0];
            currentSelected.done = !currentSelected.done;
            return [...state]
        
        case EDIT_TODO: 
            let editSelected = state.filter(obj => {
                return (obj.uuid) === payload.uuid;
            })[0];
            editSelected.name = payload.newText;
            return [...state]

        case DELETE_TODO:
            _.remove(state, (obj) => {
                return obj.uuid === payload.uuid;
            });
            return [...state]        
        
        /** FIREBASE INTEGRATION */
        case FIREBASE_FETCH_ALL: 
            return [...payload.todos]   

        default:
            return state
    }
}
export default todos;